# theme: jekyll-serif-theme
remote_theme: zerostaticthemes/jekyll-serif-theme
plugins:
  - jekyll-remote-theme
#
title: Homeoffice Week der FeG Germering
description: Bookmark this to keep an eye on my project updates!