# theme: jekyll-serif-theme
remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-theme-yat
  - jekyll-environment-variables
#
sass:
  style: compressed # possible values: nested expanded compact compressed

title: Homeoffice Week der FeG Germering
description: Bookmark this to keep an eye on my project updates!